### ISSUE TITLE
Unable to use get_exchange_rates

### ISSUE THREAD

**Issue by Eldhose-Varghese** [ddofborg/exchange_rates#1]
<img width="754" alt="Screenshot 2023-11-09 181732" src="https://github.com/ddofborg/exchange_rates/assets/143511348/793365e0-653e-47fb-914e-787d0da90e01">

I am not able to import get_exchange_rates function. Is there any other library with the same name. Can you please help me with this.

**Comment by ddofborg** [comment]
Sorry, I didn't understand your question in the first place.

You can download the file `https://github.com/ddofborg/exchange_rates/blob/main/exchange_rates.py` and import it. Save this file as `new_exchange_rates.py` for example.


Then try:

````python
from new_exchange_rates import get_exchange_rates
print( get_exchange_rates('USD', target_currencies=['EUR', 'CAD', 'USD'], on_date='2023-10-01') )
````

**Comment by Eldhose-Varghese** [comment]
I was trying to install it as a library. That was the issue. It had the exact name. Thanks buddy. Good job. Good day !!!
